### ISSUE TITLE
Crashes when used in Verminion

### ISSUE THREAD

**Issue by squidmade** [shdwp/xivPartyIcons#76]
```
   at System.Environment.get_StackTrace()
   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70
   at FFXIVClientStructs.FFXIV.Client.UI.RaptureAtkUnitManager.GetAddonByName(String name, Int32 index) in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.InteropSourceGenerators\FFXIVClientStructs.InteropSourceGenerators.CStrOverloadsGenerator\FFXIVClientStructs.FFXIV.Client.UI.RaptureAtkUnitManager.CStrOverloads.g.cs:line 17
   at PartyIcons.Api.XivApi.SafeAddonNamePlate.get_Pointer() in /work/repo/PartyIcons/Api/XivApi.cs:line 144
   at PartyIcons.Api.XivApi.SafeAddonNamePlate.GetNamePlateObject(Int32 index) in /work/repo/PartyIcons/Api/XivApi.cs:line 153
   at PartyIcons.Runtime.NPCNameplateFixer.RevertNPC() in /work/repo/PartyIcons/Runtime/NPCNameplateFixer.cs:line 62
   at PartyIcons.Runtime.NPCNameplateFixer.TaskMain(CancellationToken token) in /work/repo/PartyIcons/Runtime/NPCNameplateFixer.cs:line 40
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

https://discord.com/channels/581875019861328007/929533532185956352/1064573830011568148

**Comment by rincebrain** [comment]
Similarly, about half the time or more I seem to get a crash when I log out to the main menu:
```
Unhandled native exception occurred at ffxiv_dx11.exe+52A810
Code: C0000005
[...]
Time: 2023-02-03 01:40:20.5656314 EST
   at System.Environment.get_StackTrace()
   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70
   at FFXIVClientStructs.FFXIV.Client.UI.RaptureAtkUnitManager.GetAddonByName(String name, Int32 index) in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.InteropSourceGenerators\FFXIVClientStructs.InteropSourceGenerators.CStrOverloadsGenerator\FFXIVClientStructs.FFXIV.Client.UI.RaptureAtkUnitManager.CStrOverloads.g.cs:line 17
   at PartyIcons.Api.XivApi.SafeAddonNamePlate.get_Pointer() in /work/repo/PartyIcons/Api/XivApi.cs:line 144
   at PartyIcons.Api.XivApi.SafeAddonNamePlate.GetNamePlateObject(Int32 index) in /work/repo/PartyIcons/Api/XivApi.cs:line 153
   at PartyIcons.Runtime.NPCNameplateFixer.RevertNPC() in /work/repo/PartyIcons/Runtime/NPCNameplateFixer.cs:line 62
   at PartyIcons.Runtime.NPCNameplateFixer.TaskMain(CancellationToken token) in /work/repo/PartyIcons/Runtime/NPCNameplateFixer.cs:line 40
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
